binfmt_elf: Fix build Conflict with this commit from Sultan: Pzqqt/android_kernel_xiaomi_whyred@dad9441
../fs/binfmt_elf.c:1101:10: error: member reference type 'struct (anonymous struct at ../fs/binfmt_elf.c:686:2)' is not a pointer; did you mean to use '.'?
                    loc->elf_ex.e_type == ET_DYN && !interpreter)
                    ~~~^~
                       .
1 error generated.

Signed-off-by: NotZeetaa <rodrigo2005contente@gmail.com>